package apply_test

import (
	"os"
	"testing"

	"github.com/optioni/graft/internal/apply"
	"github.com/optioni/graft/internal/lock"
	"github.com/optioni/graft/internal/plan"
)

func TestRunWritesThePlansLock(t *testing.T) {
	t.Parallel()

	repo := newTree(t)
	src := newTree(t)
	src.file("extras/tdd/schema.yaml", "a\n")
	src.file("extras/tdd/templates/design.md", "b\n")

	p := &plan.Plan{
		Writes: []plan.Write{
			write("extras/tdd/schema.yaml", "openspec/schemas/tdd/schema.yaml"),
			write("extras/tdd/templates/design.md", "openspec/schemas/tdd/templates/design.md"),
		},
		Lock: lockOf(
			"openspec/schemas/tdd/schema.yaml",
			"openspec/schemas/tdd/templates/design.md",
		),
	}
	if err := apply.Run(repo.dir, map[string]string{"shared": src.dir}, p); err != nil {
		t.Fatalf("Run: %v", err)
	}

	data := []byte(repo.read(lock.Filename))
	if want := "# graft.lock — generated by `graft sync`. Do not edit.\n"; string(data[:len(want)]) != want {
		t.Errorf("graft.lock does not open with the generated-file header:\n%s", data)
	}

	// Parsed back through graft's own parser, not compared as a string: a lock this
	// package writes that the next run refuses to read would be the worst of the failures
	// available here, and only the parser can rule it out.
	got, err := lock.Parse(data, lock.Filename)
	if err != nil {
		t.Fatalf("parsing the lock back: %v\n%s", err, data)
	}
	if len(got.Sources) != 1 || got.Sources[0].Name != "shared" || got.Sources[0].Resolved != sha {
		t.Fatalf("parsed lock = %+v", got)
	}
	items := got.Sources[0].Items
	if len(items) != 1 || items[0].ID != "schema:tdd" || len(items[0].Files) != 2 {
		t.Fatalf("parsed items = %+v", items)
	}
}

// Byte equality, not semantic equality: a lock that reorders on every run churns the diff
// of every consumer, and a semantic comparison would not notice.
func TestRunTwiceWritesIdenticalLock(t *testing.T) {
	t.Parallel()

	repo := newTree(t)
	src := newTree(t)
	src.file("extras/a.md", "a\n")

	p := &plan.Plan{
		Writes: []plan.Write{write("extras/a.md", "docs/a.md")},
		Lock:   lockOf("docs/a.md"),
	}
	trees := map[string]string{"shared": src.dir}

	if err := apply.Run(repo.dir, trees, p); err != nil {
		t.Fatalf("first Run: %v", err)
	}
	first := repo.read(lock.Filename)

	if err := apply.Run(repo.dir, trees, p); err != nil {
		t.Fatalf("second Run: %v", err)
	}
	if second := repo.read(lock.Filename); second != first {
		t.Errorf("the lock changed between two identical runs:\nfirst:\n%s\nsecond:\n%s", first, second)
	}
}

// The residual failure the pre-flight pass cannot remove: a condition that changes, or one
// the filesystem only reports on the write itself. The lock stays the previous one, because
// a lock written now would claim a file the run never wrote.
func TestRunMidFlightFailureKeepsPreviousLock(t *testing.T) {
	t.Parallel()

	if os.Geteuid() == 0 {
		t.Skip("running as root: permission bits do not deny anything")
	}

	repo := newTree(t)
	repo.file(lock.Filename, "the previous lock\n")
	repo.file("ok/keep", "x\n")
	repo.file("locked/keep", "x\n")
	if err := os.Chmod(repo.path("locked"), 0o555); err != nil {
		t.Fatalf("Chmod: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(repo.path("locked"), 0o755) })

	src := newTree(t)
	src.file("extras/a.md", "a\n")
	src.file("extras/b.md", "b\n")

	p := &plan.Plan{
		Writes: []plan.Write{
			write("extras/a.md", "ok/a.md"),
			write("extras/b.md", "locked/b.md"),
		},
		Lock: lockOf("locked/b.md", "ok/a.md"),
	}
	err := apply.Run(repo.dir, map[string]string{"shared": src.dir}, p)
	assertErrorPrefix(t, err, `cannot write "locked/b.md": `)

	if got := repo.read(lock.Filename); got != "the previous lock\n" {
		t.Errorf("graft.lock = %q, want the previous one untouched", got)
	}
	// The first write did land. That is precisely why the lock must be the previous one:
	// a lock written now would be a record of a run that did not happen.
	if got := repo.read("ok/a.md"); got != "a\n" {
		t.Errorf("ok/a.md = %q, want %q", got, "a\n")
	}
}
