package lock_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/optioni/graft/internal/lock"
)

const sha = "fae2a30c1d4b8e9f0a2b3c4d5e6f708192a3b4c5"

const populated = `# graft.lock — generated by ` + "`graft sync`" + `. Do not edit.
version = 1

[[source]]
name     = "openspec-schemas"
git      = "github.com/optioni/openspec-schemas"
rev      = "v1.2.0"
resolved = "` + sha + `"

  [[source.item]]
  id    = "agent:apply-orchestrator"
  files = [".claude/agents/apply-orchestrator.md"]

  [[source.item]]
  id    = "schema:tdd"
  files = [
    "openspec/schemas/tdd/schema.yaml",
    "openspec/schemas/tdd/templates/design.md",
  ]
`

// oneSource renders a lock holding a single source with the given extra body lines,
// so a table case names only what it is testing.
func oneSource(body string) string {
	return `version = 1

[[source]]
name     = "openspec-schemas"
git      = "github.com/optioni/openspec-schemas"
rev      = "v1.2.0"
resolved = "` + sha + `"
` + body
}

func entries(t *testing.T, dir string) []string {
	t.Helper()
	des, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("reading %s: %v", dir, err)
	}
	names := make([]string, 0, len(des))
	for _, de := range des {
		names = append(names, de.Name())
	}
	return names
}

func TestLoad_Absent(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "graft.toml"), []byte(""), 0o600); err != nil {
		t.Fatalf("writing fixture: %v", err)
	}

	l, err := lock.Load(filepath.Join(dir, "graft.lock"))
	if err != nil {
		t.Fatalf("Load() error = %v, want nil", err)
	}
	if l.Version != 1 {
		t.Errorf("Version = %d, want 1", l.Version)
	}
	if len(l.Sources) != 0 {
		t.Errorf("len(Sources) = %d, want 0", len(l.Sources))
	}
	if got := entries(t, dir); len(got) != 1 || got[0] != "graft.toml" {
		t.Errorf("tree = %v, want only graft.toml — no graft.lock may be created", got)
	}
}

func TestParse_HeaderOnly(t *testing.T) {
	t.Parallel()

	in := "# graft.lock — generated by `graft sync`. Do not edit.\nversion = 1\n"
	l, err := lock.Parse([]byte(in), "graft.lock")
	if err != nil {
		t.Fatalf("Parse() error = %v, want nil", err)
	}
	if l.Version != 1 {
		t.Errorf("Version = %d, want 1", l.Version)
	}
	if len(l.Sources) != 0 {
		t.Errorf("len(Sources) = %d, want 0", len(l.Sources))
	}
}

func TestParse_Populated(t *testing.T) {
	t.Parallel()

	l, err := lock.Parse([]byte(populated), "graft.lock")
	if err != nil {
		t.Fatalf("Parse() error = %v, want nil", err)
	}
	if len(l.Sources) != 1 {
		t.Fatalf("len(Sources) = %d, want 1", len(l.Sources))
	}
	s := l.Sources[0]
	if s.Name != "openspec-schemas" {
		t.Errorf("Name = %q, want %q", s.Name, "openspec-schemas")
	}
	if s.Git != "github.com/optioni/openspec-schemas" {
		t.Errorf("Git = %q, want %q", s.Git, "github.com/optioni/openspec-schemas")
	}
	if s.Rev != "v1.2.0" {
		t.Errorf("Rev = %q, want %q", s.Rev, "v1.2.0")
	}
	if s.Resolved != sha {
		t.Errorf("Resolved = %q, want %q", s.Resolved, sha)
	}
	if len(s.Items) != 2 {
		t.Fatalf("len(Items) = %d, want 2", len(s.Items))
	}
	want := map[string][]string{
		"agent:apply-orchestrator": {".claude/agents/apply-orchestrator.md"},
		"schema:tdd": {
			"openspec/schemas/tdd/schema.yaml",
			"openspec/schemas/tdd/templates/design.md",
		},
	}
	for _, it := range s.Items {
		w, ok := want[it.ID]
		if !ok {
			t.Errorf("unexpected item %q", it.ID)
			continue
		}
		if strings.Join(it.Files, "\n") != strings.Join(w, "\n") {
			t.Errorf("item %q files = %v, want %v", it.ID, it.Files, w)
		}
	}
}

func TestParse_BadTOML(t *testing.T) {
	t.Parallel()

	l, err := lock.Parse([]byte("[[source]\n"), "graft.lock")
	if err == nil {
		t.Fatal("Parse() error = nil, want an error")
	}
	if !strings.HasPrefix(err.Error(), "graft.lock: ") {
		t.Errorf("Parse() error = %q, want prefix %q", err.Error(), "graft.lock: ")
	}
	if l != nil {
		t.Errorf("Parse() lock = %+v, want nil", l)
	}
}

func TestParse_VersionErrors(t *testing.T) {
	t.Parallel()

	for name, tc := range map[string]struct {
		in   string
		want string
	}{
		"missing version": {
			in: `[[source]]
name     = "openspec-schemas"
git      = "github.com/optioni/openspec-schemas"
rev      = "v1.2.0"
resolved = "` + sha + `"
`,
			want: `graft.lock: version is required`,
		},
		"newer version": {
			in: `version = 2

[[source]]
name     = "openspec-schemas"
git      = "github.com/optioni/openspec-schemas"
rev      = "v1.2.0"
resolved = "` + sha + `"
`,
			want: `graft.lock: version 2 is not supported by this graft; upgrade graft`,
		},
		"version below one": {
			in:   "version = 0\n",
			want: `graft.lock: version 0 is not a known lock version`,
		},
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			l, err := lock.Parse([]byte(tc.in), "graft.lock")
			if err == nil {
				t.Fatalf("Parse() error = nil, want %q", tc.want)
			}
			if got := err.Error(); got != tc.want {
				t.Errorf("Parse() error = %q, want %q", got, tc.want)
			}
			if l != nil {
				t.Errorf("Parse() lock = %+v, want nil — no source may be returned", l)
			}
		})
	}
}

func TestParse_SourceErrors(t *testing.T) {
	t.Parallel()

	for name, tc := range map[string]struct {
		in   string
		want string
	}{
		"missing resolved": {
			in: `version = 1

[[source]]
name = "openspec-schemas"
git  = "github.com/optioni/openspec-schemas"
rev  = "v1.2.0"
`,
			want: `graft.lock: source "openspec-schemas": resolved is required`,
		},
		"malformed resolved": {
			in: `version = 1

[[source]]
name     = "openspec-schemas"
git      = "github.com/optioni/openspec-schemas"
rev      = "v1.2.0"
resolved = "v1.2.0"
`,
			want: `graft.lock: source "openspec-schemas": resolved "v1.2.0" is not a 40-character hex sha`,
		},
		"uppercase resolved": {
			in: `version = 1

[[source]]
name     = "openspec-schemas"
git      = "github.com/optioni/openspec-schemas"
rev      = "v1.2.0"
resolved = "FAE2A30C1D4B8E9F0A2B3C4D5E6F708192A3B4C5"
`,
			want: `graft.lock: source "openspec-schemas": resolved "FAE2A30C1D4B8E9F0A2B3C4D5E6F708192A3B4C5" is not a 40-character hex sha`,
		},
		"duplicate source": {
			in: `version = 1

[[source]]
name     = "openspec-schemas"
git      = "github.com/optioni/openspec-schemas"
rev      = "v1.2.0"
resolved = "` + sha + `"

[[source]]
name     = "openspec-schemas"
git      = "github.com/optioni/openspec-schemas"
rev      = "v1.3.0"
resolved = "` + sha + `"
`,
			want: `graft.lock: duplicate source "openspec-schemas"`,
		},
		"empty source name": {
			in: `version = 1

[[source]]
name     = ""
git      = "github.com/optioni/openspec-schemas"
rev      = "v1.2.0"
resolved = "` + sha + `"
`,
			want: `graft.lock: source name is empty`,
		},
		"missing git": {
			in: `version = 1

[[source]]
name     = "openspec-schemas"
rev      = "v1.2.0"
resolved = "` + sha + `"
`,
			want: `graft.lock: source "openspec-schemas": git is required`,
		},
		"missing rev": {
			in: `version = 1

[[source]]
name     = "openspec-schemas"
git      = "github.com/optioni/openspec-schemas"
resolved = "` + sha + `"
`,
			want: `graft.lock: source "openspec-schemas": rev is required`,
		},
		"unknown source key": {
			in: `version = 1

[[source]]
name     = "openspec-schemas"
git      = "github.com/optioni/openspec-schemas"
rev      = "v1.2.0"
resolved = "` + sha + `"
sha      = "` + sha + `"
`,
			want: `graft.lock: source "openspec-schemas": unknown key "sha"`,
		},
		"unknown top-level key": {
			in:   "version = 1\nlockfile = true\n",
			want: `graft.lock: unknown key "lockfile"`,
		},
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			l, err := lock.Parse([]byte(tc.in), "graft.lock")
			if err == nil {
				t.Fatalf("Parse() error = nil, want %q", tc.want)
			}
			if got := err.Error(); got != tc.want {
				t.Errorf("Parse() error = %q, want %q", got, tc.want)
			}
			if l != nil {
				t.Errorf("Parse() lock = %+v, want nil", l)
			}
		})
	}
}

func TestParse_ItemErrors(t *testing.T) {
	t.Parallel()

	for name, tc := range map[string]struct {
		body string
		want string
	}{
		"malformed item id": {
			body: `
  [[source.item]]
  id    = "tdd"
  files = []
`,
			want: `graft.lock: source "openspec-schemas": invalid item id "tdd": want kind:name`,
		},
		"duplicate item id": {
			body: `
  [[source.item]]
  id    = "schema:tdd"
  files = []

  [[source.item]]
  id    = "schema:tdd"
  files = []
`,
			want: `graft.lock: source "openspec-schemas": duplicate item "schema:tdd"`,
		},
		"unknown item key": {
			body: `
  [[source.item]]
  id     = "schema:tdd"
  files  = []
  hashes = []
`,
			want: `graft.lock: source "openspec-schemas": item "schema:tdd": unknown key "hashes"`,
		},
		"escaping file path": {
			body: `
  [[source.item]]
  id    = "schema:tdd"
  files = ["../outside.md"]
`,
			want: `graft.lock: source "openspec-schemas": item "schema:tdd": file "../outside.md" is not a relative path inside the repo`,
		},
		"absolute file path": {
			body: `
  [[source.item]]
  id    = "schema:tdd"
  files = ["/etc/passwd"]
`,
			want: `graft.lock: source "openspec-schemas": item "schema:tdd": file "/etc/passwd" is not a relative path inside the repo`,
		},
		"parent segment mid-path": {
			body: `
  [[source.item]]
  id    = "schema:tdd"
  files = ["openspec/../../outside.md"]
`,
			want: `graft.lock: source "openspec-schemas": item "schema:tdd": file "openspec/../../outside.md" is not a relative path inside the repo`,
		},
		"empty file path": {
			body: `
  [[source.item]]
  id    = "schema:tdd"
  files = [""]
`,
			want: `graft.lock: source "openspec-schemas": item "schema:tdd": file "" is not a relative path inside the repo`,
		},
		"duplicate file": {
			body: `
  [[source.item]]
  id    = "schema:tdd"
  files = [
    "openspec/schemas/tdd/schema.yaml",
    "openspec/schemas/tdd/schema.yaml",
  ]
`,
			want: `graft.lock: source "openspec-schemas": item "schema:tdd": duplicate file "openspec/schemas/tdd/schema.yaml"`,
		},
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			l, err := lock.Parse([]byte(oneSource(tc.body)), "graft.lock")
			if err == nil {
				t.Fatalf("Parse() error = nil, want %q", tc.want)
			}
			if got := err.Error(); got != tc.want {
				t.Errorf("Parse() error = %q, want %q", got, tc.want)
			}
			if l != nil {
				t.Errorf("Parse() lock = %+v, want nil — no file list may be returned", l)
			}
		})
	}
}

func TestParse_ItemNoFiles(t *testing.T) {
	t.Parallel()

	in := oneSource(`
  [[source.item]]
  id    = "schema:tdd"
  files = []
`)
	l, err := lock.Parse([]byte(in), "graft.lock")
	if err != nil {
		t.Fatalf("Parse() error = %v, want nil", err)
	}
	if len(l.Sources) != 1 || len(l.Sources[0].Items) != 1 {
		t.Fatalf("Sources = %+v, want one source with one item", l.Sources)
	}
	if n := len(l.Sources[0].Items[0].Files); n != 0 {
		t.Errorf("len(Files) = %d, want 0", n)
	}
}

func TestLoad_Unreadable(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, "graft.lock")
	if err := os.Mkdir(path, 0o700); err != nil {
		t.Fatalf("creating directory fixture: %v", err)
	}

	if _, err := lock.Load(path); err == nil {
		t.Fatal("Load() error = nil, want an error")
	} else if !strings.HasPrefix(err.Error(), "graft.lock: ") {
		t.Errorf("Load() error = %q, want prefix %q", err.Error(), "graft.lock: ")
	}
}

func TestLoad_Populated(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, "graft.lock")
	if err := os.WriteFile(path, []byte(populated), 0o600); err != nil {
		t.Fatalf("writing fixture: %v", err)
	}

	l, err := lock.Load(path)
	if err != nil {
		t.Fatalf("Load() error = %v, want nil", err)
	}
	if len(l.Sources) != 1 {
		t.Fatalf("len(Sources) = %d, want 1", len(l.Sources))
	}
}

// TestParse_WrongTypes covers values whose TOML type does not fit the lock's shape.
// The decoder's own message describes those better than anything this package could
// invent, so only the prefix is a contract.
func TestParse_WrongTypes(t *testing.T) {
	t.Parallel()

	for name, in := range map[string]string{
		"version is a string": "version = \"one\"\n",
		"files is a string": oneSource(`
  [[source.item]]
  id    = "schema:tdd"
  files = "openspec/schemas/tdd/schema.yaml"
`),
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			l, err := lock.Parse([]byte(in), "graft.lock")
			if err == nil {
				t.Fatal("Parse() error = nil, want an error")
			}
			if !strings.HasPrefix(err.Error(), "graft.lock: ") {
				t.Errorf("Parse() error = %q, want prefix %q", err.Error(), "graft.lock: ")
			}
			if l != nil {
				t.Errorf("Parse() lock = %+v, want nil", l)
			}
		})
	}
}
