package lock

import (
	"fmt"
	"slices"
	"strings"
)

// header is the first line of every generated graft.lock.
const header = "# graft.lock — generated by `graft sync`. Do not edit.\n"

// Field widths hold the documented key alignment: source keys pad to len("resolved"),
// item keys to len("files").
const (
	sourceKeyWidth = len("resolved")
	itemKeyWidth   = len("files")
)

// Marshal renders a lock in the one layout SPEC.md documents and returns the bytes.
// It writes nothing: internal/apply is the only package permitted to touch the working
// tree, and the lock is written there, last, after every file operation has succeeded.
//
// The emitted version is always the format version this binary knows, so a lock built
// in code without one still serializes to valid bytes.
func Marshal(l *Lock) []byte {
	var b strings.Builder
	b.WriteString(header)
	fmt.Fprintf(&b, "version = %d\n", Version)

	for _, s := range normalized(l.Sources) {
		b.WriteString("\n[[source]]\n")
		writeKey(&b, "", sourceKeyWidth, "name", quote(s.Name))
		writeKey(&b, "", sourceKeyWidth, "git", quote(s.Git))
		writeKey(&b, "", sourceKeyWidth, "rev", quote(s.Rev))
		writeKey(&b, "", sourceKeyWidth, "resolved", quote(s.Resolved))

		for _, it := range s.Items {
			b.WriteString("\n  [[source.item]]\n")
			writeKey(&b, "  ", itemKeyWidth, "id", quote(it.ID))
			writeFiles(&b, it.Files)
		}
	}
	return []byte(b.String())
}

// normalized returns a deep-enough copy of sources ordered the way SPEC.md requires:
// sources by name, items by id, files by path, each by byte-wise string comparison.
// Ordering is applied here and nowhere else, so a field added to one code path cannot
// end up sorted in another and unsorted in this one. The copy matters twice over —
// Marshal must not reorder a lock its caller still holds, and sorting in place would
// make the result depend on how often Marshal had been called.
func normalized(sources []Source) []Source {
	out := slices.Clone(sources)
	for i := range out {
		items := slices.Clone(out[i].Items)
		for j := range items {
			files := slices.Clone(items[j].Files)
			slices.Sort(files)
			items[j].Files = files
		}
		slices.SortFunc(items, func(a, b Item) int { return strings.Compare(a.ID, b.ID) })
		out[i].Items = items
	}
	slices.SortFunc(out, func(a, b Source) int { return strings.Compare(a.Name, b.Name) })
	return out
}

// writeKey emits one aligned `key = value` line under the given indent.
func writeKey(b *strings.Builder, indent string, width int, key, value string) {
	b.WriteString(indent)
	b.WriteString(key)
	for i := len(key); i < width; i++ {
		b.WriteByte(' ')
	}
	b.WriteString(" = ")
	b.WriteString(value)
	b.WriteByte('\n')
}

// writeFiles emits the files array. An empty list is `[]`, a single file stays inline,
// and two or more explode one per line — including a trailing comma after the last, so
// adding a file touches one line of the diff rather than two.
func writeFiles(b *strings.Builder, files []string) {
	switch len(files) {
	case 0:
		writeKey(b, "  ", itemKeyWidth, "files", "[]")
	case 1:
		writeKey(b, "  ", itemKeyWidth, "files", "["+quote(files[0])+"]")
	default:
		writeKey(b, "  ", itemKeyWidth, "files", "[")
		for _, f := range files {
			b.WriteString("    ")
			b.WriteString(quote(f))
			b.WriteString(",\n")
		}
		b.WriteString("  ]\n")
	}
}

// quote renders s as a TOML basic string. Every value graft emits goes through it, so
// a path holding a quote or a backslash survives the round trip instead of producing a
// lock graft cannot read back.
func quote(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\b':
			b.WriteString(`\b`)
		case '\t':
			b.WriteString(`\t`)
		case '\n':
			b.WriteString(`\n`)
		case '\f':
			b.WriteString(`\f`)
		case '\r':
			b.WriteString(`\r`)
		default:
			if r < 0x20 || r == 0x7f {
				fmt.Fprintf(&b, `\u%04X`, r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}
