package lock_test

import (
	"bytes"
	"os"
	"strings"
	"testing"

	"github.com/optioni/graft/internal/lock"
)

// golden is the canonical layout SPEC.md documents, read as bytes and never written.
func golden(t *testing.T) []byte {
	t.Helper()
	b, err := os.ReadFile("testdata/canonical.lock")
	if err != nil {
		t.Fatalf("reading golden file: %v", err)
	}
	return b
}

// canonicalLock is the value the golden file serializes from.
func canonicalLock() *lock.Lock {
	return &lock.Lock{
		Version: 1,
		Sources: []lock.Source{{
			Name:     "openspec-schemas",
			Git:      "github.com/optioni/openspec-schemas",
			Rev:      "v1.2.0",
			Resolved: sha,
			Items: []lock.Item{
				{ID: "agent:apply-orchestrator", Files: []string{".claude/agents/apply-orchestrator.md"}},
				{ID: "schema:tdd", Files: []string{
					"openspec/schemas/tdd/schema.yaml",
					"openspec/schemas/tdd/templates/design.md",
				}},
			},
		}},
	}
}

func TestMarshal_Golden(t *testing.T) {
	t.Parallel()

	got := lock.Marshal(canonicalLock())
	if want := golden(t); !bytes.Equal(got, want) {
		t.Errorf("Marshal() bytes differ from testdata/canonical.lock\n got:\n%s\nwant:\n%s", got, want)
	}
}

func TestMarshal_FilesLayout(t *testing.T) {
	t.Parallel()

	for name, tc := range map[string]struct {
		files []string
		want  string
	}{
		"zero files": {nil, "  files = []\n"},
		"one file": {
			[]string{"a/b.md"},
			"  files = [\"a/b.md\"]\n",
		},
		"two files": {
			[]string{"a/b.md", "a/c.md"},
			"  files = [\n    \"a/b.md\",\n    \"a/c.md\",\n  ]\n",
		},
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			l := &lock.Lock{Version: 1, Sources: []lock.Source{{
				Name: "s", Git: "g", Rev: "v1", Resolved: sha,
				Items: []lock.Item{{ID: "k:n", Files: tc.files}},
			}}}
			got := string(lock.Marshal(l))
			if !strings.Contains(got, tc.want) {
				t.Errorf("Marshal() = %q, want it to contain %q", got, tc.want)
			}
		})
	}
}

func TestMarshal_Empty(t *testing.T) {
	t.Parallel()

	want := "# graft.lock — generated by `graft sync`. Do not edit.\nversion = 1\n"
	got := string(lock.Marshal(&lock.Lock{Version: 1}))
	if got != want {
		t.Errorf("Marshal() = %q, want %q", got, want)
	}
}

func TestMarshal_Escaping(t *testing.T) {
	t.Parallel()

	const path = `dir/od"d\name.md`
	l := &lock.Lock{Version: 1, Sources: []lock.Source{{
		Name: "s", Git: "g", Rev: "v1", Resolved: sha,
		Items: []lock.Item{{ID: "k:n", Files: []string{path}}},
	}}}

	out := lock.Marshal(l)
	if want := `"dir/od\"d\\name.md"`; !strings.Contains(string(out), want) {
		t.Errorf("Marshal() = %s, want it to contain %s", out, want)
	}

	back, err := lock.Parse(out, "graft.lock")
	if err != nil {
		t.Fatalf("Parse() of marshalled bytes error = %v, want nil", err)
	}
	if got := back.Sources[0].Items[0].Files[0]; got != path {
		t.Errorf("round-tripped path = %q, want %q", got, path)
	}
}

// TestMarshal_EscapingControlChars covers the rest of the TOML basic-string escape
// table. A POSIX filename may hold any byte but NUL and /, and a lock graft cannot
// read back is worse than an ugly one.
func TestMarshal_EscapingControlChars(t *testing.T) {
	t.Parallel()

	const path = "a\b\tb\nc\fd\re\x01f.md"
	l := &lock.Lock{Version: 1, Sources: []lock.Source{{
		Name: "s", Git: "g", Rev: "v1", Resolved: sha,
		Items: []lock.Item{{ID: "k:n", Files: []string{path}}},
	}}}

	out := lock.Marshal(l)
	if want := `"a\b\tb\nc\fd\re\u0001f.md"`; !strings.Contains(string(out), want) {
		t.Errorf("Marshal() = %s, want it to contain %s", out, want)
	}

	back, err := lock.Parse(out, "graft.lock")
	if err != nil {
		t.Fatalf("Parse() of marshalled bytes error = %v, want nil", err)
	}
	if got := back.Sources[0].Items[0].Files[0]; got != path {
		t.Errorf("round-tripped path = %q, want %q", got, path)
	}
}
